<a href="https://colab.research.google.com/github/sriharikk/FDVA_241501093/blob/main/FDVA_exp2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import requests
from io import StringIO
from google.colab import files


csv_data = {
    "Name": ["Arun", "Priya", "Rahul", "Divya", "Kiran"],
    "Age": [21, 22, 20, 23, 21],
    "City": ["Chennai", "Madurai", "Coimbatore", "Salem", "Trichy"]
}

df_csv_original = pd.DataFrame(csv_data)
df_csv_original.to_csv(
    "/content/test_Y3wMUE5_7gLdaTN.csv",
    index=False
)

print("STEP 1: CSV file created successfully")
df_csv = pd.read_csv("/content/test_Y3wMUE5_7gLdaTN.csv")
display(df_csv.head())

excel_data = {
    "Year": [2020, 2021, 2022, 2023, 2024],
    "Investment": [10000, 12000, 15000, 18000, 22000],
    "Return": [500, 800, 1200, 1600, 2200]
}

df_excel_original = pd.DataFrame(excel_data)
df_excel_original.to_excel(
    "/content/Historicalinvesttemp.xlsx",
    sheet_name="Sheet1",
    index=False
)

print("\nSTEP 2: Excel file created successfully")
df_excel = pd.read_excel(
    "/content/Historicalinvesttemp.xlsx",
    sheet_name="Sheet1"
)
display(df_excel.head())


print("\nSTEP 3: Retrieving GDP data from Wikipedia")

url = "https://en.wikipedia.org/wiki/List_of_countries_by_GDP_(nominal)"

try:
    headers = {
        "User-Agent": (
            "Mozilla/5.0 (X11; Linux x86_64) "
            "AppleWebKit/537.36 Chrome/120.0 Safari/537.36"
        )
    }

    response = requests.get(url, headers=headers, timeout=30)
    response.raise_for_status()

    tables = pd.read_html(StringIO(response.text))

    if len(tables) > 0:

        df_web = tables[0]

        print("Wikipedia table retrieved successfully")
        display(df_web.head())

    else:
        raise ValueError("No HTML tables found")

except Exception as e:
    print("Wikipedia data could not be retrieved:", e)
    print("Using sample GDP data instead.")

    df_web = pd.DataFrame({
        "Country": [
            "United States", "China", "Germany", "India", "Japan"
        ],
        "GDP_USD_Trillion": [29.2, 18.7, 4.7, 3.9, 4.0],
        "Year": [2024, 2024, 2024, 2024, 2024]
    })

    display(df_web.head())


print("\nSTEP 4: Exporting Excel data")

df = pd.read_excel("/content/Historicalinvesttemp.xlsx")

output_path = "/content/weeeeee.xlsx"
df.to_excel(output_path, index=False)

print("Excel file saved successfully as weeeeee.xlsx")
display(df.head())

df_web.to_csv("/content/GDP_data.csv", index=False)
print("\nGDP data saved as GDP_data.csv")


print("\nSTEP 5: Downloading output files")

files.download("/content/weeeeee.xlsx")
files.download("/content/GDP_data.csv")

print("\nEXPERIMENT COMPLETED!")

STEP 1: CSV file created successfully

    Name  Age        City
0   Arun   21     Chennai
1  Priya   22     Madurai
2  Rahul   20  Coimbatore
3  Divya   23       Salem
4  Kiran   21      Trichy

STEP 2: Excel file created successfully

   Year  Investment  Return
0  2020       10000     500
1  2021       12000     800
2  2022       15000    1200
3  2023       18000    1600
4  2024       22000    2200

STEP 3: Retrieving GDP data from Wikipedia
Wikipedia table retrieved successfully

                                                   0
0  Largest economies in the world by nominal GDP ...

STEP 4: Exporting Excel data
Excel file saved successfully as weeeeee.xlsx

   Year  Investment  Return
0  2020       10000     500
1  2021       12000     800
2  2022       15000    1200
3  2023       18000    1600
4  2024       22000    2200

GDP data saved as GDP_data.csv

STEP 5: Downloading output files

EXPERIMENT COMPLETED!